package events

import "github.com/bk2004/rl-statsapi-parser/internal/publisher"

type CountdownBeginData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var CountdownBegin publisher.Publisher[CountdownBeginData] = publisher.New[CountdownBeginData]("CountdownBegin")
// Generated by scripts/structsToGo.js