package events

import "github.com/bk2004/rl-statsapi-parser/internal/publisher"

type GoalReplayEndData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var GoalReplayEnd publisher.Publisher[GoalReplayEndData] = publisher.New[GoalReplayEndData]("GoalReplayEnd")
// Generated by scripts/structsToGo.js