package events

import "github.com/bk2004/rl-statsapi-parser/internal/publisher"

type GoalReplayStartData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var GoalReplayStart publisher.Publisher[GoalReplayStartData] = publisher.New[GoalReplayStartData]("GoalReplayStart")
// Generated by scripts/structsToGo.js