package events

import "github.com/bk2004/rl-statsapi-parser/internal/publisher"

type MatchUnpausedData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var MatchUnpaused publisher.Publisher[MatchUnpausedData] = publisher.New[MatchUnpausedData]("MatchUnpaused")
// Generated by scripts/structsToGo.js