package events

import "rl-statsapi-parser/internal/publisher"

type MatchCreatedData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var MatchCreated publisher.Publisher[MatchCreatedData] = publisher.New[MatchCreatedData]("MatchCreated")
// Generated by scripts/structsToGo.js