package events

import "rl-statsapi-parser/internal/publisher"

type MatchInitializedData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var MatchInitialized publisher.Publisher[MatchInitializedData] = publisher.New[MatchInitializedData]("MatchInitialized")
// Generated by scripts/structsToGo.js