package events

import "rl-statsapi-parser/internal/publisher"

type MatchDestroyedData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var MatchDestroyed publisher.Publisher[MatchDestroyedData] = publisher.New[MatchDestroyedData]("MatchDestroyed")
// Generated by scripts/structsToGo.js