package events

import "rl-statsapi-parser/internal/publisher"

type MatchPausedData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var MatchPaused publisher.Publisher[MatchPausedData] = publisher.New[MatchPausedData]("MatchPaused")
// Generated by scripts/structsToGo.js