package events

import "rl-statsapi-parser/internal/publisher"

type MatchEndedData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
	WinnerTeamNum int64 `json:"WinnerTeamNum"` // Team index of the winning team.
}

var MatchEnded publisher.Publisher[MatchEndedData] = publisher.New[MatchEndedData]("MatchEnded")
// Generated by scripts/structsToGo.js