package events

import "github.com/bk2004/rl-statsapi-parser/internal/publisher"

type ReplayCreatedData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var ReplayCreated publisher.Publisher[ReplayCreatedData] = publisher.New[ReplayCreatedData]("ReplayCreated")
// Generated by scripts/structsToGo.js