package events

// Sent at the start of each round when the countdown starts.
type CountdownBeginData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}
// Generated by scripts/structsToGo.js