package events

// Sent when a goal replay starts.
type GoalReplayStartData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}
// Generated by scripts/structsToGo.js