package events

// Sent when the ball explodes during a goal replay. If the replay is skipped this event will not fire.
type GoalReplayWillEndData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}
// Generated by scripts/structsToGo.js