package events

// Sent when all teams are created and replicated.
type MatchCreatedData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}
// Generated by scripts/structsToGo.js