package events

// Sent when the game is unpaused by a match admin.
type MatchUnpausedData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}
// Generated by scripts/structsToGo.js