package events

// Sent when the first countdown starts.
type MatchInitializedData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}
// Generated by scripts/structsToGo.js