package events

// Sent when the game enters the podium state after the match ends.
type PodiumStartData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}
// Generated by scripts/structsToGo.js