package events

// Sent when the game enters the active state (after the countdown finishes).
type RoundStartedData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}
// Generated by scripts/structsToGo.js