package events

import "rl-statsapi-parser/publisher"

type CountdownBeginData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var CountdownBegin publisher.Publisher[CountdownBeginData] = publisher.New[CountdownBeginData]("CountdownBegin")
// Generated by scripts/structsToGo.js