package events

import "rl-statsapi-parser/publisher"

type GoalReplayStartData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var GoalReplayStart publisher.Publisher[GoalReplayStartData] = publisher.New[GoalReplayStartData]("GoalReplayStart")
// Generated by scripts/structsToGo.js