package events

import "rl-statsapi-parser/publisher"

type GoalReplayWillEndData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var GoalReplayWillEnd publisher.Publisher[GoalReplayWillEndData] = publisher.New[GoalReplayWillEndData]("GoalReplayWillEnd")
// Generated by scripts/structsToGo.js