package events

import "rl-statsapi-parser/publisher"

type MatchUnpausedData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var MatchUnpaused publisher.Publisher[MatchUnpausedData] = publisher.New[MatchUnpausedData]("MatchUnpaused")
// Generated by scripts/structsToGo.js