package events

import "rl-statsapi-parser/publisher"

type PodiumStartData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var PodiumStart publisher.Publisher[PodiumStartData] = publisher.New[PodiumStartData]("PodiumStart")
// Generated by scripts/structsToGo.js