package events

import "rl-statsapi-parser/publisher"

type ReplayCreatedData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var ReplayCreated publisher.Publisher[ReplayCreatedData] = publisher.New[ReplayCreatedData]("ReplayCreated")
// Generated by scripts/structsToGo.js