package events

import "rl-statsapi-parser/publisher"

type RoundStartedData struct {
	MatchGuid string `json:"MatchGuid"` // Only set for online or LAN matches.
}

var RoundStarted publisher.Publisher[RoundStartedData] = publisher.New[RoundStartedData]("RoundStarted")
// Generated by scripts/structsToGo.js