import { join } from "path";
import { writeFile, readFile, appendFile } from "fs/promises";

const JSON_DEST = join(import.meta.dirname, '..', 'data');
const EVENT_NAMES_NAME = "eventnames.json"
const EVENT_DESCRIPTIONS_NAME = "eventdescriptions.json"
const EVENT_STRUCTS_NAME = "eventstructures.json"
const EVENT_STRUCTS_DEST = join(import.meta.dirname, '..', 'internal', 'events');
const EVENT_LISTENER_DEST = join(import.meta.dirname, '..', 'internal', 'listener', 'listener.go');
const SUBSCRIBER_EXPORT_DEST = join(import.meta.dirname, '..', 'main.go');

const LISTENER_SWITCH_START = '// START LISTEN EVENT SWITCH'
const LISTENER_SWITCH_END = '// END LISTEN EVENT SWITCH'

const SUBSCRIBER_EXPORT_START = '// START SUBSCRIBER EXPORT'
const SUBSCRIBER_EXPORT_END = '// END SUBSCRIBER EXPORT'

const EVENT_STRUCT_PREAMBLE = `package events\n
import "rl-statsapi-parser/internal/publisher"\n\n`;

const STATIC_TYPE_TRANSLATIONS = {
    string: "string",
    bool: "bool",
    int: "int64",
    float: "float64",
    vector: "struct {X float64; Y float64; Z float64}"
}

const DYNAMIC_TYPE_TRANSLATIONS = {
    object: "struct{",
    array: "[]struct{"
}

async function readJSON(filename) {
    const text = await readFile(filename, "utf8");
    return JSON.parse(text);
}

async function appendWithTabs(dest, content, tabCount) {
    const tabs = "\t".repeat(tabCount);
    return await appendFile(dest, `${tabs}${content}`);
}

async function writeField(filename, fieldName, fieldStruct, tabs) {
    const publicFieldName = fieldName[0].toUpperCase() + fieldName.slice(1);
    await appendWithTabs(filename, `${publicFieldName} ${STATIC_TYPE_TRANSLATIONS[fieldStruct.fieldType] || DYNAMIC_TYPE_TRANSLATIONS[fieldStruct.fieldType]}${STATIC_TYPE_TRANSLATIONS[fieldStruct.fieldType] ? ` \`json:"${fieldName}"\`` : ''} // ${fieldStruct.description}\n`, tabs)

    // If dynamic type, need to recursive write nested fields
    if (DYNAMIC_TYPE_TRANSLATIONS[fieldStruct.fieldType]) {
        // Recursive call to write nested fields
        for (const [nestedFieldName, nestedFieldStruct] of Object.entries(fieldStruct.subFields)) {
            await writeField(filename, nestedFieldName, nestedFieldStruct, tabs + 1);
        }
        await appendWithTabs(filename, `} \`json:"${fieldName}"\`\n`, tabs);
    }
}

async function writeStructToFile(eventName, struct) {
    // Reset file if it exists, give it the preamble
    const dest = join(EVENT_STRUCTS_DEST, `${eventName}.go`);
    await writeFile(dest, EVENT_STRUCT_PREAMBLE);

    await appendFile(dest, `type ${eventName}Data struct {\n`)

    const tabs = 1; // Start at 1 tab for written fields
    for (const [fieldName, fieldStruct] of Object.entries(struct)) {
        await writeField(dest, fieldName, fieldStruct, tabs);
    }
    await appendFile(dest, '}\n');

    // Exported publisher
    await appendFile(dest, `\nvar ${eventName} publisher.Publisher[${eventName}Data] = publisher.New[${eventName}Data]("${eventName}")\n`)

    await appendFile(dest, '// Generated by scripts/structsToGo.js');
}

async function writeListenerSwitch(eventNames) {
    let fileContents = await readFile(EVENT_LISTENER_DEST, "utf8");
    const switchStartIndex = fileContents.indexOf(LISTENER_SWITCH_START);
    const switchEndIndex = fileContents.indexOf(LISTENER_SWITCH_END);

    if (switchStartIndex === -1 || switchEndIndex === -1) {
        console.error("Could not find listener switch in file.");
        return;
    }

    let newFileContents = fileContents.substring(0, switchStartIndex + LISTENER_SWITCH_START.length) + "\n";
    for (const eventName of eventNames) {
        newFileContents += `\tcase "${eventName}":\n`;
        newFileContents += `\t\tvar parsed events.${eventName}Data\n`;
        newFileContents += `\t\tif err := json.Unmarshal(data, &parsed); err != nil {\n`;
        newFileContents += `\t\t\tfmt.Printf("Failed to unmarshal ${eventName} data: %v.", err)\n`;
        newFileContents += `\t\t\treturn\n`;
        newFileContents += `\t\t}\n`;
        newFileContents += `\t\tevents.${eventName}.Publish(parsed)\n`;
    }
    newFileContents += fileContents.substring(switchEndIndex);

    await writeFile(EVENT_LISTENER_DEST, newFileContents);
}

async function writeSubscriberExports(eventNames, eventDescriptions) {
    let fileContents = await readFile(SUBSCRIBER_EXPORT_DEST, "utf8");
    const exportStartIndex = fileContents.indexOf(SUBSCRIBER_EXPORT_START);
    const exportEndIndex = fileContents.indexOf(SUBSCRIBER_EXPORT_END);

    if (exportStartIndex === -1 || exportEndIndex === -1) {
        console.error("Could not find subscriber exports in file.");
        return;
    }

    let newFileContents = fileContents.substring(0, exportStartIndex + SUBSCRIBER_EXPORT_START.length) + "\n\n";
    for (let i = 0; i < eventNames.length; i++) {
        const eventName = eventNames[i];
        const description = eventDescriptions[i] || "No description available.";
        // Write description above export of newSubscriber for event
        newFileContents += `\t// ${description}\n`;
        newFileContents += `\t${eventName} = newSubscriber(events.${eventName})\n`;
    }
    newFileContents += fileContents.substring(exportEndIndex);

    await writeFile(SUBSCRIBER_EXPORT_DEST, newFileContents);
}

async function main() {
    try {
        const eventNames = await readJSON(join(JSON_DEST, EVENT_NAMES_NAME));
        const eventDescriptions = await readJSON(join(JSON_DEST, EVENT_DESCRIPTIONS_NAME));
        const eventStructs = await readJSON(join(JSON_DEST, EVENT_STRUCTS_NAME));

        for (const [name, struct] of Object.entries(eventStructs)) {
            console.log(`Writing struct for event ${name} to ${EVENT_STRUCTS_DEST}/${name}.go`)
            await writeStructToFile(name, struct);
            console.log(`Finished writing to ${EVENT_STRUCTS_DEST}/${name}.go`)
        }

        console.log(`Writing listener switch to ${EVENT_LISTENER_DEST}`)
        await writeListenerSwitch(eventNames);
        console.log(`Finished writing listener switch to ${EVENT_LISTENER_DEST}`);

        console.log(`Writing subscriber exports to ${SUBSCRIBER_EXPORT_DEST}`)
        await writeSubscriberExports(eventNames, eventDescriptions);
        console.log(`Finished writing subscriber exports to ${SUBSCRIBER_EXPORT_DEST}`);
    } catch (e) {
        console.error("Error:", e);
    }
}

main();